# Generated by Django 5.2.5 on 2025-08-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('clave', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=8)),
                ('descripcion', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pblret1', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Publico Retir L1')),
                ('pblrep1', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Publico Reparto L1')),
                ('pblret4', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Publico Retira L4')),
                ('pblrep4', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Publico Reparto L4')),
                ('ultact', models.DateField(verbose_name='Ultima Actualizacion')),
                ('imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('visible', models.CharField(max_length=1, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
    ]
