# Generated by Django 5.2.5 on 2025-08-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='campoa1',
            field=models.CharField(default='', max_length=1, verbose_name='Campo A1'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='espesor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='articulos',
            name='estado',
            field=models.CharField(default='', max_length=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='formular',
            field=models.CharField(default='', max_length=20, verbose_name='Formula'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='grupo',
            field=models.CharField(default='', max_length=3, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='mts2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Lista 1'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Lista 4'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='preciopub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Publico'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='recargo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Recargo'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='redferre',
            field=models.CharField(default='', max_length=1, verbose_name='Red Ferreteria'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='reducida',
            field=models.CharField(default='', max_length=1, verbose_name='Reducida'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='reparto',
            field=models.CharField(default='', max_length=2, verbose_name='Reparto'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='tiporeparto',
            field=models.CharField(default='', max_length=1, verbose_name='Tipo Reparto'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
