# Generated by Django 5.2.5 on 2025-08-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_articulos_campoa1_articulos_espesor_articulos_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='formular',
            new_name='formula',
        ),
    ]
