# Generated by Django 5.2.5 on 2025-08-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_formular_articulos_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('lista', models.CharField(max_length=1)),
                ('punitorio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Punitorio')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('distancia', models.IntegerField(default=0)),
                ('fletep1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fletetn1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fletep4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fletetn4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reparto', models.CharField(default='', max_length=1)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
    ]
