# Generated by Django 5.2.5 on 2025-08-15 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_formapago_localidades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cliente', models.CharField(max_length=50, unique=True)),
                ('lista_precio', models.CharField(choices=[('1', 'Lista 1'), ('4', 'Lista 4')], max_length=1)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_responsable_iva', models.CharField(choices=[('C', 'Responsable Inscripto'), ('F', 'Consumidor Final'), ('M', 'Monotributista'), ('E', 'Exento')], max_length=2)),
                ('regimen_percepcion', models.CharField(blank=True, choices=[('', 'No alcanzado'), ('60', 'Régimen de IIBB')], max_length=2)),
                ('cuit', models.CharField(blank=True, max_length=13, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('codigo_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.localidades')),
                ('condicion_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formapago')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
