# Generated by Django 5.2.5 on 2025-08-20 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='lista_precio',
            field=models.CharField(choices=[(' ', 'Todos'), ('1', 'Lista 1'), ('4', 'Lista 4')], max_length=1),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='lista',
            field=models.CharField(blank=True, choices=[(' ', 'Todos'), ('1', 'Lista 1'), ('4', 'Lista 4')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='localidades',
            name='fletep1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Flete % Lista 1'),
        ),
        migrations.AlterField(
            model_name='localidades',
            name='fletep4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Flete % Lista 4'),
        ),
        migrations.AlterField(
            model_name='localidades',
            name='fletetn1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Flete TN Lista 1'),
        ),
        migrations.AlterField(
            model_name='localidades',
            name='fletetn4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Flete TN Lista 4'),
        ),
        migrations.AlterField(
            model_name='localidades',
            name='reparto',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='Localidad con Reparto'),
        ),
        migrations.CreateModel(
            name='BonificacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde_articulo', models.CharField(max_length=8, verbose_name='Desde Artículo')),
                ('hasta_articulo', models.CharField(max_length=8, verbose_name='Hasta Artículo')),
                ('bonificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
            options={
                'verbose_name': 'Bonificación por Cliente',
                'verbose_name_plural': 'Bonificaciones por Cliente',
            },
        ),
    ]
