# Generated by Django 5.2.5 on 2025-08-22 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_registrosesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosesion',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
