# Generated by Django 5.2.5 on 2025-09-12 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_pedido_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_precio', to='api.articulos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_precio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta de Precio',
                'verbose_name_plural': 'Consultas de Precios',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', 'fecha_hora'], name='api_consult_usuario_2ab12b_idx'), models.Index(fields=['articulo', 'fecha_hora'], name='api_consult_articul_7ecff6_idx')],
            },
        ),
    ]
