# Generated by Django 5.2.5 on 2025-10-04 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_consultaprecio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='clave',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_cliente',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.CreateModel(
            name='CarritoTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad o m² según el tipo de artículo', max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.articulos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_temporal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrito Temporal',
                'verbose_name_plural': 'Carritos Temporales',
                'ordering': ['-fecha_modificado'],
                'indexes': [models.Index(fields=['user', 'fecha_modificado'], name='api_carrito_user_id_f21b4a_idx'), models.Index(fields=['fecha_modificado'], name='api_carrito_fecha_m_a77fb1_idx')],
                'unique_together': {('user', 'articulo')},
            },
        ),
    ]
