# Generated by Django 5.2.5 on 2026-02-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_pedido_modalidad_con_impuestos'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='discontinuado',
            field=models.CharField(default='', max_length=1, verbose_name='Discontinuado'),
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.AutoField(db_column='idOferta', primary_key=True, serialize=False)),
                ('vence', models.DateField(db_column='vence')),
                ('articulo', models.ForeignKey(db_column='articulo', on_delete=django.db.models.deletion.CASCADE, to='api.articulos')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'db_table': 'ofertas',
                'ordering': ['-vence'],
            },
        ),
    ]
