# Generated by Django 5.2.5 on 2026-02-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_articulos_discontinuado_ofertas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ofertas',
        ),
    ]
