# Generated by Django 5.2.5 on 2026-02-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_delete_ofertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='oferta',
            field=models.CharField(default='', max_length=1, verbose_name='Oferta'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='vencimiento_oferta',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Oferta'),
        ),
    ]
