# Generated by Django 5.2.5 on 2026-02-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_articulo_vista'),
        ('api', '0021_articulos_oferta_articulos_vencimiento_oferta'),
    ]

    operations = [
    ]
