# Generated by Django 5.2.5 on 2026-03-30 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20260207_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('target_url', models.URLField(max_length=2000)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referer', models.CharField(blank=True, max_length=2000, null=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Apertura de Link',
                'verbose_name_plural': 'Aperturas de Links',
                'ordering': ['-opened_at'],
            },
        ),
    ]
