# Generated by Django 5.2.5 on 2026-03-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_linkopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='empresa_id',
            field=models.IntegerField(default=1),
        ),
    ]
