# Generated by Django 5.2.5 on 2026-05-20 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_articulos_empresa_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortTrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('token', models.CharField(db_index=True, max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('target_url', models.URLField(max_length=2000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Link Corto de Tracking',
                'verbose_name_plural': 'Links Cortos de Tracking',
                'ordering': ['-created_at'],
            },
        ),
    ]
