# Generated by Django 5.2.5 on 2026-05-22 18:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_shorttrackinglink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('origen', models.CharField(choices=[('chat_local', 'Chat local'), ('whatsapp', 'WhatsApp'), ('api', 'API')], db_index=True, max_length=30)),
                ('telefono', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('mensaje_usuario', models.TextField()),
                ('respuesta_bot', models.TextField(blank=True)),
                ('intencion', models.CharField(db_index=True, default='fallback', max_length=50)),
                ('estado', models.CharField(choices=[('ok', 'OK'), ('ambiguous', 'Ambiguo'), ('not_found', 'No encontrado'), ('fallback', 'Fallback'), ('error', 'Error')], db_index=True, default='ok', max_length=30)),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('error_tecnico', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Conversacion Bot',
                'verbose_name_plural': 'Logs de Conversaciones Bot',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['origen', 'fecha_hora'], name='api_botconv_origen_075d55_idx'), models.Index(fields=['intencion', 'estado'], name='api_botconv_intenci_12810d_idx')],
            },
        ),
    ]
