"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from decouple import config
import os
from pathlib import Path

from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Leer variables del .env
DEBUG = config('DEBUG', default=False, cast=bool)
SECRET_KEY = config('SECRET_KEY')

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.0.200', '192.168.0.195', 'ventas.ferreteriaavenida.com.ar', '186.5.245.12']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Terceros
    'rest_framework',
    'corsheaders',    
    
    'api',
    'graficos',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # 👉 Tu middleware personalizado (debe ir después de AuthenticationMiddleware)
    'api.middleware.ActivityTrackingMiddleware',  # Cambia 'tu_app' por tu nombre real    
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE'),
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    },
    'fasa': {
        'ENGINE': config('FASA_DB_ENGINE'),
        'NAME': config('FASA_DB_NAME'),
        'USER': config('FASA_DB_USER'),
        'PASSWORD': config('FASA_DB_PASSWORD'),
        'HOST': config('FASA_DB_HOST', default=config('DB_HOST')),
        'PORT': config('FASA_DB_PORT', default=config('DB_PORT')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# Internacionalización (Español - Argentina)
LANGUAGE_CODE = config('LANGUAGE_CODE', default='es-ar')
TIME_ZONE = config('TIME_ZONE', default='America/Argentina/Buenos_Aires')
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ROOT_URLCONF = 'backend.urls'

# CORS - Permitir Vue (localhost:5173)
# CORS - Leer lista de orígenes
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='http://localhost:5173,http://localhost:5174').split(',')

# Autenticación con JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),     # Aumentado a 30 min
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),        # 7 días
    'ROTATE_REFRESH_TOKENS': True,                      # Nuevo refresh al usar uno
    'BLACKLIST_AFTER_ROTATION': True,                   # Invalida el refresh usado
  # 🔽 Clave: define cómo se llaman las cookies
    'AUTH_COOKIE': 'access_token',  # Nombre de la cookie del access
    'AUTH_COOKIE_REFRESH': 'refresh_token',  # Nombre de la cookie del refresh
    'AUTH_COOKIE_HTTP_ONLY': True,   # No accesible por JS
    'AUTH_COOKIE_SECURE': False,     # True en producción con HTTPS
    'AUTH_COOKIE_SAMESITE': 'Lax',   # 'Lax' o 'None' si es cross-origin
    'AUTH_COOKIE_PATH': '/',         # Disponible en toda la app    
}
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Empresa activa (filtrar artículos por `empresa_id`)
EMPRESA_ID = config('EMPRESA_ID', default=1, cast=int)

# Configuración de Email
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='mail.ferreteriaavenida.com.ar')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)
EMAIL_RECIPIENT = config('EMAIL_RECIPIENT', default='')
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)

# WhatsApp bot MVP
WHATSAPP_VERIFY_TOKEN = config('WHATSAPP_VERIFY_TOKEN', default='')
WHATSAPP_ACCESS_TOKEN = config('WHATSAPP_ACCESS_TOKEN', default='')
WHATSAPP_PHONE_NUMBER_ID = config('WHATSAPP_PHONE_NUMBER_ID', default='')
WHATSAPP_BOT_USERNAME = config('WHATSAPP_BOT_USERNAME', default='')
BOT_AGENT_ENABLED = config('BOT_AGENT_ENABLED', default=False, cast=bool)
BOT_AGENT_TEST_CHAT_ENABLED = config('BOT_AGENT_TEST_CHAT_ENABLED', default=False, cast=bool)

# OpenRouter bot fallback
OPENROUTER_API_KEY = config('OPENROUTER_API_KEY', default='')
OPENROUTER_MODEL = config('OPENROUTER_MODEL', default='openrouter/free')
OPENROUTER_BASE_URL = config('OPENROUTER_BASE_URL', default='https://openrouter.ai/api/v1')
OPENROUTER_REFERER = config('OPENROUTER_REFERER', default='http://localhost/revendedores')
OPENROUTER_APP_TITLE = config('OPENROUTER_APP_TITLE', default='Revendedores Bot')
OPENROUTER_TIMEOUT = config('OPENROUTER_TIMEOUT', default=30, cast=int)
OPENROUTER_MAX_TOKENS = config('OPENROUTER_MAX_TOKENS', default=180, cast=int)

# Admins que recibirán los errores
ADMINS = [
    ('Admin Ferretería', 'oscar@ferreteriaavenida.com.ar'),
]

import os
from pathlib import Path

# Asegúrate de que el directorio 'logs' exista dentro de tu proyecto
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',  # Solo errores y superiores
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'django_errors.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',  # Cambia a 'DEBUG' si quieres ver TODO
            'propagate': True,
        },
        'api': {  # Logger específico para tu app 'api'
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
