# Generated by Django 5.2.5 on 2025-09-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=45)),
                ('NETO', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('IVA', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('NETO_NETO', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('PRECIO', models.DecimalField(decimal_places=3, default=0.0, max_digits=13)),
                ('UNITARIO', models.DecimalField(decimal_places=3, default=0.0, max_digits=13)),
                ('CANTIDAD', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('FECHA', models.DateField()),
                ('NetoRenglon', models.DecimalField(blank=True, decimal_places=11, max_digits=33, null=True)),
                ('total', models.DecimalField(decimal_places=7, default=0.0, max_digits=23)),
                ('PercepcionDGR', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('dgrdetalle', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('LOCALIDAD', models.CharField(max_length=4)),
                ('CODIGO', models.CharField(default='F', max_length=2)),
                ('LISTA', models.CharField(max_length=1)),
                ('CLAVE', models.CharField(max_length=8)),
                ('REPARTO', models.CharField(max_length=8)),
                ('COMP', models.CharField(default='0', max_length=12)),
                ('REGIVA', models.CharField(max_length=4)),
                ('IDMOVI', models.IntegerField(default=0)),
                ('CLASE', models.CharField(max_length=1)),
                ('VENDEDOR', models.CharField(max_length=2)),
                ('FLETE', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('DESCPRET', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('NOTA', models.CharField(max_length=50)),
                ('UNIDAD', models.CharField(max_length=8)),
                ('PAGO', models.CharField(default='00', max_length=2)),
                ('CUOTAPAGO', models.IntegerField(default=1)),
                ('FECHAVEN', models.DateField()),
                ('FECHA1VENC', models.DateField()),
                ('fletetransp', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('boni', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('COSTO', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('Introduccion', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('CONTADO', models.CharField(default='S', max_length=1)),
                ('IDSTOCKVE', models.IntegerField(default=0)),
                ('DETEXT', models.TextField(blank=True, null=True)),
                ('aliciva', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('DESCAD', models.CharField(max_length=40)),
                ('Procesado', models.BooleanField(default=False)),
                ('PAGOANT', models.BooleanField(default=False)),
                ('Item', models.CharField(max_length=3)),
                ('GastoTar', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('DES1', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('PUNITORIO', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('REPARTE', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'facturas',
                'managed': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id_sucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'sucursales',
                'managed': False,
            },
        ),
    ]
